"""initial schema

Revision ID: 75ae1b8b7aa3
Revises: 
Create Date: 2026-07-02 00:56:15.771849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ae1b8b7aa3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisor_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('current_variant', sa.Text(), nullable=False),
    sa.Column('suggested_variant', sa.Text(), nullable=False),
    sa.Column('expected_uplift_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('expected_revenue_impact', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('result_sample_size_per_arm', sa.Integer(), nullable=True),
    sa.Column('result_control_conversions', sa.Integer(), nullable=True),
    sa.Column('result_control_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('result_variant_conversions', sa.Integer(), nullable=True),
    sa.Column('result_variant_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('result_observed_uplift_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('result_p_value', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('result_is_significant', sa.Boolean(), nullable=True),
    sa.Column('result_ci_low', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('result_ci_high', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('growth_twin_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('predicted_mrr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('predicted_churn_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('predicted_activation_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('predicted_expansion_mrr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('predicted_paid_conversion_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('conversion_model_auc', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('conversion_model_accuracy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('churn_model_auc', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('churn_model_accuracy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('conversion_feature_importance', sa.JSON(), nullable=False),
    sa.Column('churn_feature_importance', sa.JSON(), nullable=False),
    sa.Column('insufficient_data', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revenue_leaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('monthly_impact', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('revenue_impact', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effort', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trial_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('signup_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('project_created_at', sa.DateTime(), nullable=True),
    sa.Column('team_invited_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('churned_at', sa.DateTime(), nullable=True),
    sa.Column('mrr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trial_users')
    op.drop_table('roadmap_items')
    op.drop_table('revenue_leaks')
    op.drop_table('growth_twin_snapshots')
    op.drop_table('experiments')
    op.drop_table('advisor_messages')
    op.drop_table('companies')
    # ### end Alembic commands ###
